version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... making s3"
    - aws s3api create-bucket --bucket my-bucket-dewankar --region us-east-1 --object-ownership BucketOwnerEnforced
    - zip -r deployment_package.zip lambda_function.py
    - aws s3 cp deployment_package.zip s3://my-bucket-dewankar/lambda/lambda1

  post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name  hello_world --zip-file fileb://deployment_package.zip
artifacts:
  type: zip
  paths:
    - '*'
